; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
default_envs = nodo1

[env:nodo1]
platform = espressif32
board = featheresp32
framework = arduino
monitor_speed = 115200
build_flags =
    -D NODE_NUM=1
lib_deps = 
	adafruit/DHT sensor library @ 1.4.6
	beegee-tokyo/DHT sensor library for ESPx@^1.19
	knolleary/PubSubClient@^2.8

[env:nodo2]
platform = espressif32
board = featheresp32
framework = arduino
monitor_speed = 115200
build_flags =
  -D NODE_NUM=2
lib_deps =
  adafruit/DHT sensor library @ 1.4.6
  beegee-tokyo/DHT sensor library for ESPx @ ^1.19
  knolleary/PubSubClient @ ^2.8

[env:nodo3]
platform = espressif32
board = featheresp32
framework = arduino
monitor_speed = 115200
build_flags =
  -D NODE_NUM=3
lib_deps =
  adafruit/DHT sensor library @ 1.4.6
  beegee-tokyo/DHT sensor library for ESPx @ ^1.19
  knolleary/PubSubClient @ ^2.8

[env:nodo4]
platform = espressif32
board = featheresp32
framework = arduino
monitor_speed = 115200
build_flags =
  -D NODE_NUM=4
lib_deps =
  adafruit/DHT sensor library @ 1.4.6
  beegee-tokyo/DHT sensor library for ESPx @ ^1.19
  knolleary/PubSubClient @ ^2.8